[notes]
append = """
- By default, the Supabase client sets `persistSession` to true and attempts to store the session in local storage. When using the Supabase client in an environment that doesn't support local storage, you might notice the following warning message being logged:

  > No storage option exists to persist the session, which may result in unexpected behavior when using Auth. If you want to set `persistSession` to true, please provide a storage option or you may set `persistSession` to false to disable this warning.

  This warning message can be safely ignored if you're not using Auth on the server-side. If you are using Auth and you want to set `persistSession` to true, you will need to provide a custom storage implementation that follows [this interface](https://github.com/supabase/gotrue-js/blob/master/src/lib/types.ts#L1027)."""

[[examples]]
id = "create-auth-client"
name = "Create auth client"

code = """
```js
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(supabase_url, anon_key)
```"""

[[examples]]
id = "create-auth-client-server-side"
name = "Create auth client (server-side)"

code = """
```js
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(supabase_url, anon_key, {
auth: {
autoRefreshToken: false,
persistSession: false,
detectSessionInUrl: false
}
})
```"""
